[workspace]
resolver = "3"
members = ["mkwpp-api-compat-layer-core", "mkwpp-api-compat-layer-macros", "mkwpp-api-compat-layer-wasm"]

[workspace.lints.clippy]
duplicate_mod = "deny"
fn_to_numeric_cast_any = "deny"
manual_string_new = "deny"
needless_borrow = "deny"
semicolon_if_nothing_returned = "warn"
implicit_clone = "deny"
too_many_arguments = "allow"

[workspace.lints.rust]
unused_imports = "warn"

