[package]
name = "mkwpp-api-compat-layer-core"
version = "0.1.1"
edition = "2024"

[dependencies]
actix-web = { version = "4.11.0", optional = true }
either_field = "1.2.0"
futures = "0.3.31"
js-sys = { version = "0.3.77", optional = true }
paste = "1.0.15"
serde = { version = "1.0.219", features = ["derive"] }
serde-wasm-bindgen = { version = "0.6.5", optional = true }
serde_json = "1.0.142"
serde_with = "3.16.1"
wasm-bindgen = { version = "0.2.100", optional = true }
wasm-bindgen-futures = { version = "0.4.50", optional = true }
wasm-bindgen-multi-value-xform = "0.2.100"
web-sys = { version = "0.3.77", optional = true, features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
] }

[dev-dependencies]
strum = { version = "*", features = ["derive"] }

[features]
default = ["rust-actix"]
rust-actix = ["dep:actix-web"]
typescript-wasm = ["dep:wasm-bindgen", "dep:wasm-bindgen-futures", "dep:js-sys", "dep:web-sys", "dep:serde-wasm-bindgen"]

[lints]
workspace = true
